name: pr

on:
  pull_request_target: # https://github.com/dependabot/dependabot-core/issues/3253
    branches: [ master ]

defaults:
  run:
    shell: bash

permissions:
  pull-requests: write
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm
      # - run: npm install -g npm@7

      - name: Set up NPM authentication
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.READ_ONLY_PAT }}" >> ~/.npmrc

      - name: Set up NPM authentication for dry release
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.ACTIONS_TOKEN }}" >> ~/.npmrc

      - uses: cycjimmy/semantic-release-action@v2.6.0
        id: semantic # need an `id` for output variables
        with:
          dry_run: true
          semantic_version: 17
          extra_plugins: |
            @semantic-release/git@9.0.1
            @semantic-release/changelog@6.0.0
            @semantic-release/exec@6.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          NPM_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

  dependabot-approve-and-automerge:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
