name: release

on:
  push:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  # publish-artifact:
    # permissions:
      # issues: write
    # runs-on: ubuntu-latest
    # steps:
      # - uses: actions/checkout@v2.4.0
        # with:
          # token: ${{ secrets.ACTIONS_TOKEN }}
          # persist-credentials: false
      # - uses: actions/setup-node@v2
        # with:
          # node-version: 14
          # cache: npm
      # # - run: npm install -g npm@7

      # - name: Set up NPM authentication
        # run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.ACTIONS_TOKEN }}" >> ~/.npmrc

      # - uses: cycjimmy/semantic-release-action@v2.6.0
        # id: semantic # need an `id` for output variables
        # with:
          # semantic_version: 17
          # extra_plugins: |
            # @semantic-release/git@9.0.1
            # @semantic-release/changelog@6.0.0
            # @semantic-release/exec@6.0.1
        # env:
          # GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          # NPM_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          # NODE_AUTH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

  deploy-docs:
    runs-on: ubuntu-latest
    needs: publish-artifact
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          persist-credentials: false

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com

      - run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d public -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
